import Link from "next/link";
import { ArrowRight, BarChart3, CheckCircle2, Clock3, ShieldCheck, Sparkles } from "lucide-react";
import { Logo } from "@/components/logo";

export default function Home() {
  return <><header className="site-header"><div className="container"><Logo/><div className="header-actions"><Link className="btn btn-ghost" href="/login">Ingresar</Link><Link className="btn btn-primary" href="/register">Crear cuenta <ArrowRight size={16}/></Link></div></div></header>
    <main><section className="hero"><div className="container hero-grid"><div><p className="eyebrow">Preparación PAES · Competencia Matemática 1</p><h1>Practica con <span>criterio.</span><br/>Avanza con evidencia.</h1><p className="hero-copy">Ensayos M1 de 65 preguntas, corrección detallada y un mapa claro de lo que ya dominas y lo que conviene reforzar.</p><div className="hero-actions"><Link href="/register" className="btn btn-primary">Comenzar mi primer ensayo <ArrowRight size={17}/></Link><Link href="#metodo" className="btn btn-secondary">Conocer el método</Link></div><div className="trust-row"><span><CheckCircle2 size={15}/> Temario Admisión 2027</span><span><ShieldCheck size={15}/> Respuestas protegidas</span><span><Clock3 size={15}/> 2 h 20 min</span></div></div>
      <div className="hero-board" aria-label="Vista previa de una pregunta"><div className="board-top"><span>Ensayo M1 · Pregunta 38 de 65</span><b>01:17:42</b></div><div className="board-question"><p className="number">REPRESENTAR · DATOS</p><h3>El gráfico muestra los préstamos registrados en una biblioteca durante cuatro días. ¿Cuál fue el promedio diario?</h3><div className="mini-chart"><span style={{height:"42%"}}/><span style={{height:"76%"}}/><span style={{height:"58%"}}/><span style={{height:"92%"}}/></div><div className="mini-options"><span>A · 18</span><span>B · 21</span><span>C · 24</span><span>D · 27</span></div></div></div></div></section>
      <section className="section" id="metodo"><div className="container"><div className="section-heading"><p className="eyebrow">Más que un puntaje</p><h2>Una práctica que te muestra <span className="serif">por qué</span> te equivocas.</h2></div><div className="feature-grid"><article className="feature"><Sparkles/><h3>Ensayos equilibrados</h3><p>Un blueprint distribuye ejes, habilidades, dificultad y recursos visuales antes de seleccionar cada pregunta.</p></article><article className="feature"><BarChart3/><h3>Diagnóstico accionable</h3><p>Revisa rendimiento por eje, habilidad y dificultad. Las recomendaciones se basan solo en tus respuestas.</p></article><article className="feature"><ShieldCheck/><h3>Corrección segura</h3><p>Las respuestas correctas nunca viajan al navegador mientras el ensayo está activo. La corrección ocurre en el servidor.</p></article></div></div></section>
      <section className="section"><div className="container"><div className="cta-band"><h2>Tu próximo avance empieza con una pregunta bien elegida.</h2><Link className="btn btn-secondary" href="/register">Crear cuenta gratis <ArrowRight size={17}/></Link></div></div></section></main>
    <footer className="site-footer"><div className="container"><Logo/><span>Plataforma educativa independiente. No afiliada a DEMRE.</span></div></footer></>;
}
